### ISSUE TITLE
Going in and out of fullscreen creates a window inside of the minecraft window

### ISSUE THREAD

**Issue by DanyGames2014** [MasterSlenderTR/Beta-1.7.4-Issues#1]
When i go in and out of fullscreen using F8 or F11 another window appears inside the main one, it can be freely resized
![Snímek obrazovky 2023-04-03 010640](https://user-images.githubusercontent.com/24621316/229384724-fefe04d8-4915-4a35-b961-a780161e7600.png)

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
