### ISSUE TITLE
When sleeping in a bed the photo mode is upside down

### ISSUE THREAD

**Issue by DanyGames2014** [MasterSlenderTR/Beta-1.7.4-Issues#10]
When sleeping in a bed you can freely rotate your head, the default orientation makes it that the photo mode is upside down, or in some other inverted rotation
![Snímek obrazovky 2023-04-03 230110](https://user-images.githubusercontent.com/24621316/229659072-d27d80a3-376e-4652-8ac5-801207f06c8e.png)
![Snímek obrazovky 2023-04-03 223405](https://user-images.githubusercontent.com/24621316/229659089-bd1f9f3a-52ff-47d2-92a3-2ff66a72e5b8.png)

Here with a 90 degree tilt you can see its inverted 
![Snímek obrazovky 2023-04-03 230126](https://user-images.githubusercontent.com/24621316/229659109-7403b83a-2250-4170-9ace-350b26a67783.png)

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
