### ISSUE TITLE
Sometimes on higher render distances further away chunks get visually corrupted

### ISSUE THREAD

**Issue by DanyGames2014** [MasterSlenderTR/Beta-1.7.4-Issues#12]
Happens on Far and Normal too, but mostly happens on higher than Far render distances, the same chunk loads for all chunks beyond the far limit and still is there even when you approach it, forcing you to change your render distance to force all the chunks to reload

These are 2 different worlds but it seems like the same glitched chunk visual is being rendered between them
![Snímek obrazovky 2023-04-03 224311](https://user-images.githubusercontent.com/24621316/229659674-3010cbc3-e0a9-4d7c-bf9c-a463a973df64.png)
![Snímek obrazovky 2023-04-03 013507](https://user-images.githubusercontent.com/24621316/229659690-394009ab-1e09-4063-bec4-e98c2661a8c5.png)
![Snímek obrazovky 2023-04-03 013454](https://user-images.githubusercontent.com/24621316/229659702-c07528b0-952c-4fd0-830e-c3231a899635.png)
![Snímek obrazovky 2023-04-03 013434](https://user-images.githubusercontent.com/24621316/229659710-ba803230-bb9b-47eb-91bb-da82dd19ea17.png)
![Snímek obrazovky 2023-04-03 005608](https://user-images.githubusercontent.com/24621316/229659719-e9247930-2561-4310-b89b-5038c2cb6ef7.png)

Here's some settings that could affect it
![Snímek obrazovky 2023-04-03 013548](https://user-images.githubusercontent.com/24621316/229659880-fc06ec13-d23e-4c38-bd07-3743297c664f.png)
![Snímek obrazovky 2023-04-03 013539](https://user-images.githubusercontent.com/24621316/229659884-1d10f234-baf9-447e-adba-5f9432ccc999.png)

**Comment by MasterSlenderTR** [comment]
The issue has been fixed in PRE2
