### ISSUE TITLE
Included DeadMansChest plugin does not seem to be working

### ISSUE THREAD

**Issue by spyguy26** [MasterSlenderTR/Beta-1.7.4-Issues#13]
while in multiplayer even with two chests in the inventory death does not result in a chest being created
but deadmans chest is shown as being loaded in the server's log
as shown here
https://gist.github.com/spyguy26/5d3112982c966e067b653dd80347d406

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
