### ISSUE TITLE
Only Endermen Spawning in caves and at night

### ISSUE THREAD

**Issue by DullishCrab94** [MasterSlenderTR/Beta-1.7.4-Issues#17]
It seems that all animal spawns have been fixed but for some reason im only seeing endermen spawn at night and in caves i havent seen any other hostile mob and for some reasons there's always hundreds of them spawning

**Comment by MasterSlenderTR** [comment]
Try disabling Enderman mod in /mods folder and test to see if it changes anything

**Comment by DullishCrab94** [comment]
I did it and fixed it with most of the hostile mobs though i havent seen many mo creatures mobs mainly vanilla mobs are spawning

**Comment by MasterSlenderTR** [comment]
Your issue is now fixed with release of PRE3.
