### ISSUE TITLE
items in chest disappear

### ISSUE THREAD

**Issue by DullishCrab94** [MasterSlenderTR/Beta-1.7.4-Issues#18]
i had a chest full of items and all the items in the chest vanished and also all battle tower chests are empty and the spawners are broken

**Comment by MasterSlenderTR** [comment]
Did any stacktrace show up when that happened?

**Comment by DullishCrab94** [comment]
Everything was completely gone i tried destroying the chest but when i did nothing came out of it except the chests

**Comment by MasterSlenderTR** [comment]
I hope you were taking autosaves, there's a mod in the modpack that takes auto-world backups.

also I saw happening this to a guy who forgot to enable MoCreaturesSP when upgrading from PRE1 to PRE2, their issue with empty chests got fixed when they enabled MoCreaturesSP. Can you check if this is the case for you? (If this issue happens again, can you please check if there's a error message on console?)

**Comment by DullishCrab94** [comment]
Yeah iam using mo creatures sp i made sure of it before i launched pre 2. It happened when i went inside a battletower and looked in the chest. The chest was empty but after that all chests were empty including the one with all my stuff and yes if it happens again ill check for an error
