### ISSUE TITLE
Spawner particles don't go away after breaking

### ISSUE THREAD

**Issue by manchyy** [MasterSlenderTR/Beta-1.7.4-Issues#19]
After breaking a mob spawner, the flames still render until you relog.

![CG09tNU](https://user-images.githubusercontent.com/37485545/230855355-086761be-39b5-4c92-bc6d-fd98dcf69818.png)

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
