### ISSUE TITLE
Nether Fence recipe bug

### ISSUE THREAD

**Issue by manchyy** [MasterSlenderTR/Beta-1.7.4-Issues#22]
There is a recipe that looks accidental; it only appears after pressing U on redstone blocks, but when pressing R on the nether fence it doesn't show it, although it does work.

![tGoikpn](https://user-images.githubusercontent.com/37485545/231540598-f0ab639c-488d-469f-afce-f1636cef4e4f.png)
![PI0Zxrr](https://user-images.githubusercontent.com/37485545/231540661-3e0b3a5e-164b-4ac7-9775-cd2d4568bb69.png)

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
