### ISSUE TITLE
Unintended double door behaviour 

### ISSUE THREAD

**Issue by manchyy** [MasterSlenderTR/Beta-1.7.4-Issues#23]
Double doors are glitched, as in you cannot place them the same orientation or they will bug out. In the vanilla b1.7.3 they work just fine.

https://user-images.githubusercontent.com/37485545/231562656-f66d4bf7-8557-48f9-86d6-8fced8911037.mp4

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
