### ISSUE TITLE
cobalt, golden, and bloody mossy cobblestone share recipes.

### ISSUE THREAD

**Issue by Zekken01** [MasterSlenderTR/Beta-1.7.4-Issues#24]
![image](https://user-images.githubusercontent.com/19770864/231630782-410715d9-f90c-444b-a8be-556ee0ef2b22.png)
![image](https://user-images.githubusercontent.com/19770864/231630799-e356170e-3a6f-47b6-b290-0da3b6f0e7d9.png)
![image](https://user-images.githubusercontent.com/19770864/231630820-12f37f6d-2b1f-4967-abc1-ba80f80d3129.png)
Only the blue cobble is craftable

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
