### ISSUE TITLE
Unintended cactus behaviour

### ISSUE THREAD

**Issue by manchyy** [MasterSlenderTR/Beta-1.7.4-Issues#25]
Similar to https://github.com/MasterSlenderTR/Beta-1.7.4-Issues/issues/23, video explains it all

https://user-images.githubusercontent.com/37485545/231879106-f506abbc-5d2a-4c97-b089-96fb1dc3e98e.mp4

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
