### ISSUE TITLE
Redpower's covers don't return the right amount when broken

### ISSUE THREAD

**Issue by manchyy** [MasterSlenderTR/Beta-1.7.4-Issues#26]
When multiple covers are placed adjacent to each other, upon breaking they usually don't return the correct amount of covers used

https://user-images.githubusercontent.com/37485545/231880601-c042c37a-102e-4542-946c-e3d080900e0b.mp4

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
