### ISSUE TITLE
nw#a not reobfuscated

### ISSUE THREAD

**Issue by ThexXTURBOXx** [MasterSlenderTR/Beta-1.7.4-Issues#28]
The method `nw.a()V` or `Tesselator#draw` is not correctly reobfuscated inside the Beta 1.7.4 Client jarmod.
The file `nw.class` contains a function `draw` which should rather be called `a`.
In order to fix this, two things are possible: Correctly reobfuscate this function or add another "delegator" function.
This [zip file](https://github.com/MasterSlenderTR/Beta-1.7.4-Issues/files/11952061/nw.zip) contains exactly the same `nw.class` file as yours, except for a delegator function that has been added.
This fixed compatibility with (for example) Block Helper.

Please keep in mind that I have not checked for even more errors than that.
There could still be more functions that have not been reobfuscated correctly (this should be checked properly)

**Comment by ThexXTURBOXx** [comment]
Never mind, found another function that has not been reobfuscated correctly: `fd.o()Ljava/util/List;`

Edit: [Here](https://github.com/MasterSlenderTR/Beta-1.7.4-Issues/files/11962220/fd.zip) is a fixed version of the `fd` class file.

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
