### ISSUE TITLE
Very few mobs spawn

### ISSUE THREAD

**Issue by DullishCrab94** [MasterSlenderTR/Beta-1.7.4-Issues#4]
Sorry to bother you again but im not really sure if this is a bug or something intended but I’ve hardly seen mobs of any kind spawn ill see maybe one or 2 but never what i normally see in beta 1.7.3 i tried messing around with global mod settings and am using mo creatures sp but i cant figure out what is going on

**Comment by MasterSlenderTR** [comment]
The issue has been fixed in PRE2
