### ISSUE TITLE
MAtmos music volume setting broken

### ISSUE THREAD

**Issue by TheWe5t** [MasterSlenderTR/Beta-1.7.4-Issues#5]
Normally opening the inventory and holding the assigned button (f9 in this modpack and f7 by default iirc) is supposed to close the inventory and open music volume settings. 
Doing so here results with grayed out text while the inventory remains open (image below)
Additionally I tried this MAtmos backport outside of the modpack and it works great except trying to access the settings crashes the game.
![image](https://user-images.githubusercontent.com/129763138/229533861-ff617aeb-9ef1-4359-bf11-8f9e194371ea.png)

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
