### ISSUE TITLE
Invisible Waypoint Beacons after reload

### ISSUE THREAD

**Issue by DanyGames2014** [MasterSlenderTR/Beta-1.7.4-Issues#8]
I can only see beacons for waypoints that i made in the current playsession, all previous waypoints are still there on the map but invisible, turning them off and on doesnt help either
![obrazek](https://user-images.githubusercontent.com/24621316/229625772-1f2445a7-23a3-4137-98a9-9681fcedb037.png)

**Comment by MasterSlenderTR** [comment]
Thanks for reporting, your issue is now fixed with release of PRE3.
