### ISSUE TITLE
Breaking wooden doors only gives the bottom door part

### ISSUE THREAD

**Issue by DanyGames2014** [MasterSlenderTR/Beta-1.7.4-Issues#9]
When i break doors the item that drops is only the bottom part, if i break the top i get 2 of them
![obrazek](https://user-images.githubusercontent.com/24621316/229658810-f70b7dbb-08c3-4457-8ca0-f071e4678b57.png)
Placed down they look like this
![obrazek](https://user-images.githubusercontent.com/24621316/229658899-4a5747f3-f014-4213-ad27-c5db90424fa8.png)

**Comment by MasterSlenderTR** [comment]
The issue has been fixed in PRE2
